
C4Context
    title System Context Diagram for CaCi
    
    Person(user, "User", "A person with an account, who may belong to circles of other people.")

    Enterprise_Boundary(b1, "CaCi Platform") {
        System(System_caci, "CaCi", "The core system of the CaCi platform.")
        SystemDb(System_caci_db, "The CaCi operational store")
    }
    
    System_Ext(System_llm, "LLM", "Answers questions, categorises information based on context from CaCi")
    System_Ext(System_comms, "Comms", "Communicates with the user via Email, Txt, PushNotifications ...")

    Rel(user, System_caci, "Uses")
    Rel(System_caci, System_caci_db, "Reads/Writes to", "DB Specific")
    Rel(System_caci, System_llm, "Asks questions with embedded brain context")