import type { CircleController, CirclesError } from '../circles/index.js';
import type { JsonValue } from '../graph_store/index.js';
import type { Result } from '../circles/index.js';
import { clearCookie } from './cookies.js';
import { NO_BODY, unknownKey } from './common.js';
import type { ApiResponse, Route, RouteContext } from './router.js';

export interface CircleRoutesOptions {
  readonly circles: CircleController;
  /** The session cookie's name; the same one the other routes use. Default `caci_session`. */
  readonly cookieName?: string;
  /** Whether the cookie is `Secure` (needed to clear it with the same attributes). Default `false`. */
  readonly secureCookies?: boolean;
}

/** HTTP status for each `CirclesError` code: one table, for the circle routes and the invitation routes. */
export const CIRCLE_STATUS_OF: Readonly<Record<CirclesError['code'], number>> = Object.freeze({
  INVALID_INPUT: 422,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  CONFLICT: 409,
  UNAUTHENTICATED: 401,
  LAST_OWNER: 409,
  LIMIT_REACHED: 429,
  THROTTLED: 429,
  STORAGE_ERROR: 500,
});

/** Same shape as every other failure the server sends. Messages come from the controller and are already fixed per kind. */
export function circleErrorResponse(error: CirclesError, cookies?: readonly string[]): ApiResponse {
  return {
    status: CIRCLE_STATUS_OF[error.code] ?? 500,
    body: { error: { code: error.code, message: error.message, ...(error.field === undefined ? {} : { field: error.field }) } },
    ...(error.retryAfterMs === undefined ? {} : { retryAfterSeconds: Math.ceil(error.retryAfterMs / 1000) }),
    ...(cookies === undefined ? {} : { cookies }),
  };
}

const asJson = (value: unknown): JsonValue => value as JsonValue;

/** The page controls of a query string: a `limit` that is not a number is passed on as NaN, so the controller refuses it by name. */
export function pageOf(query: Readonly<Record<string, string>>): { limit?: number; cursor?: string } {
  return {
    ...(query.limit === undefined ? {} : { limit: query.limit.trim() === '' ? Number.NaN : Number(query.limit) }),
    ...(query.cursor === undefined ? {} : { cursor: query.cursor }),
  };
}

/** What a route handler returns before it is turned into a response: a success response or a controller error. */
type Done = Result<ApiResponse, CirclesError>;

/**
 * A route that needs a session. `bodyKeys` are the body fields the route accepts (`undefined` means the
 * route reads the whole body itself, for the controller to check); `queryKeys` the query parameters it
 * accepts. Anything else is refused by name, and a refused session also clears a stale cookie.
 */
export function circleRoute(
  options: Pick<CircleRoutesOptions, 'cookieName' | 'secureCookies'>,
  rules: { readonly body?: readonly string[]; readonly query?: readonly string[] },
  run: (ctx: RouteContext, token: string) => Promise<Done>,
): (ctx: RouteContext) => Promise<ApiResponse> {
  const cookieName = options.cookieName ?? 'caci_session';
  const secure = options.secureCookies ?? false;
  return async (ctx) => {
    const token = ctx.cookies[cookieName];
    if (token === undefined) return circleErrorResponse({ code: 'UNAUTHENTICATED', message: 'not signed in' });
    const stray = Object.keys(ctx.query).find((key) => !(rules.query ?? []).includes(key));
    if (stray !== undefined) return circleErrorResponse({ code: 'INVALID_INPUT', message: `${stray} is not accepted here`, field: stray });
    if (rules.body !== undefined) {
      const bad = unknownKey(ctx.body ?? NO_BODY, rules.body);
      if (bad !== undefined) return circleErrorResponse({ code: 'INVALID_INPUT', message: bad.message, ...(bad.field === undefined ? {} : { field: bad.field }) });
    }
    const done = await run(ctx, token);
    if (done.ok) return done.value;
    return circleErrorResponse(done.error, done.error.code === 'UNAUTHENTICATED' ? [clearCookie(cookieName, { secure })] : undefined);
  };
}

export const ok = (response: ApiResponse): Done => ({ ok: true, value: response });
export { asJson };

/**
 * The circle and member routes of R-004. Every route needs the session cookie; nothing here names the
 * caller, the controller takes it from the session. Ids in paths are generated by the service
 * (`c...`, `u...`), so the path pattern is enough. Someone who is not in a circle gets the answer for a
 * circle that does not exist, from every route.
 */
export function createCircleRoutes(options: CircleRoutesOptions): readonly Route[] {
  const { circles } = options;
  const route = (rules: { body?: readonly string[]; query?: readonly string[] }, run: (ctx: RouteContext, token: string) => Promise<Done>) => circleRoute(options, rules, run);

  return [
    {
      method: 'POST',
      path: '/api/circles',
      handler: route({}, async (ctx, token) => {
        const made = await circles.create(token, ctx.body);
        return made.ok ? ok({ status: 201, body: { circle: asJson(made.value) } }) : made;
      }),
    },
    {
      method: 'GET',
      path: '/api/circles',
      handler: route({ body: [], query: ['limit', 'cursor'] }, async (ctx, token) => {
        const listed = await circles.list(token, pageOf(ctx.query));
        return listed.ok ? ok({ status: 200, body: asJson(listed.value) }) : listed;
      }),
    },
    {
      method: 'GET',
      path: '/api/circles/:id',
      handler: route({ body: [] }, async (ctx, token) => {
        const got = await circles.get(token, ctx.params.id);
        return got.ok ? ok({ status: 200, body: { circle: asJson(got.value) } }) : got;
      }),
    },
    {
      method: 'PATCH',
      path: '/api/circles/:id',
      handler: route({}, async (ctx, token) => {
        const changed = await circles.update(token, ctx.params.id, ctx.body);
        return changed.ok ? ok({ status: 200, body: { circle: asJson(changed.value) } }) : changed;
      }),
    },
    {
      method: 'DELETE',
      path: '/api/circles/:id',
      handler: route({ body: [] }, async (ctx, token) => {
        const done = await circles.delete(token, ctx.params.id);
        return done.ok ? ok({ status: 204 }) : done;
      }),
    },
    {
      method: 'GET',
      path: '/api/circles/:id/members',
      handler: route({ body: [], query: ['limit', 'cursor'] }, async (ctx, token) => {
        const listed = await circles.members(token, ctx.params.id, pageOf(ctx.query));
        return listed.ok ? ok({ status: 200, body: asJson(listed.value) }) : listed;
      }),
    },
    {
      method: 'PATCH',
      path: '/api/circles/:id/members/:userId',
      handler: route({}, async (ctx, token) => {
        const changed = await circles.changeRole(token, ctx.params.id, ctx.params.userId, ctx.body);
        return changed.ok ? ok({ status: 200, body: { member: asJson(changed.value) } }) : changed;
      }),
    },
    {
      method: 'DELETE',
      path: '/api/circles/:id/members/:userId',
      handler: route({ body: [] }, async (ctx, token) => {
        const done = await circles.removeMember(token, ctx.params.id, ctx.params.userId);
        return done.ok ? ok({ status: 204 }) : done;
      }),
    },
    {
      method: 'POST',
      path: '/api/circles/:id/leave',
      handler: route({ body: [] }, async (ctx, token) => {
        const done = await circles.leave(token, ctx.params.id);
        return done.ok ? ok({ status: 204 }) : done;
      }),
    },
  ];
}
